# Generated by Django 5.2.3 on 2025-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('standard', 'Standard User'), ('guest', 'Guest')], default='standard', max_length=10),
        ),
    ]
