# Generated by Django 5.2.3 on 2025-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device hostname', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('device_type', models.CharField(max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22, help_text='SSH port')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
                'ordering': ['name'],
            },
        ),
    ]
