# Generated by Django 5.2.3 on 2025-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('server', 'Server'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='vendor',
            field=models.CharField(blank=True, choices=[('cisco', 'Cisco'), ('juniper', 'Juniper'), ('arista', 'Arista'), ('hp', 'HP'), ('dell', 'Dell'), ('other', 'Other')], max_length=50),
        ),
    ]
